nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.0-rc.11.cjs

# temporary compatibility
packageExtensions:
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@types/react-html-parser@*":
    dependencies:
      htmlparser2: "*"
  "@types/htmlparser2@*":
    dependencies:
      domutils: "*"
  "styled-jsx@*":
    dependencies:
      process: "*"
  "node-fetch@*":
    dependencies:
      encoding: "*"
